# Generated by Django 3.2.7 on 2021-10-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_festivals_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(blank=True, max_length=30, null=True)),
                ('salutation', models.CharField(choices=[('Mrs.', 'Mrs.'), ('Mr.', 'Mr.'), ('Miss.', 'Miss.')], default='Mr.', max_length=20, null=True)),
                ('full_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('postal_address', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('numberofperson', models.IntegerField(blank=True, null=True)),
                ('arival', models.DateField(blank=True, null=True)),
                ('pickup', models.BooleanField(blank=True, default=False)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
