# Generated by Django 3.2.7 on 2021-10-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pickup',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='salutation',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss.', 'Miss.')], default='Mr.', max_length=20, null=True),
        ),
    ]
