# Generated by Django 3.2.7 on 2021-10-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20211005_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pay',
            field=models.CharField(blank=True, choices=[('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Traveller Cheque', 'Traveller Cheque')], default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='salutation',
            field=models.CharField(choices=[('Miss.', 'Miss.'), ('Mrs.', 'Mrs.'), ('Mr.', 'Mr.')], default='Mr.', max_length=20, null=True),
        ),
    ]
