# Generated by Django 3.2.7 on 2021-10-05 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20211005_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(blank=True, max_length=70)),
                ('overview', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='pay',
            field=models.CharField(blank=True, choices=[('Credit Card', 'Credit Card'), ('Cash', 'Cash'), ('Traveller Cheque', 'Traveller Cheque'), ('Bank Transfer', 'Bank Transfer')], default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='salutation',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Miss.', 'Miss.'), ('Mrs.', 'Mrs.')], default='Mr.', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.trips')),
            ],
        ),
    ]
