# Generated by Django 3.2.7 on 2021-10-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20211005_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pay',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Credit Card', 'Credit Card'), ('Traveller Cheque', 'Traveller Cheque')], default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='salutation',
            field=models.CharField(choices=[('Miss.', 'Miss.'), ('Mrs.', 'Mrs.'), ('Mr.', 'Mr.')], default='Mr.', max_length=20, null=True),
        ),
    ]
