# Generated by Django 3.2.7 on 2021-10-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20211005_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pay',
            field=models.CharField(blank=True, choices=[('Credit Card', 'Credit Card'), ('Cash', 'Cash'), ('Traveller Cheque', 'Traveller Cheque'), ('Bank Transfer', 'Bank Transfer')], default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='salutation',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Miss.', 'Miss.'), ('Mrs.', 'Mrs.')], default='Mr.', max_length=20, null=True),
        ),
    ]
