# Generated by Django 3.2.7 on 2021-10-08 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20211008_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pay',
            field=models.CharField(blank=True, choices=[('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Traveller Cheque', 'Traveller Cheque'), ('Credit Card', 'Credit Card')], default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='salutation',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss.', 'Miss.')], default='Mr.', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Pros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_pros', to='home.trips')),
            ],
        ),
        migrations.CreateModel(
            name='Cons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_cons', to='home.trips')),
            ],
        ),
    ]
