# Generated by Django 3.2.7 on 2021-10-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20211008_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('comment', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='pay',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Traveller Cheque', 'Traveller Cheque'), ('Bank Transfer', 'Bank Transfer')], default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='salutation',
            field=models.CharField(choices=[('Miss.', 'Miss.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], default='Mr.', max_length=20, null=True),
        ),
    ]
