# Generated by Django 3.2.7 on 2021-10-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20211008_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='publishable',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pay',
            field=models.CharField(blank=True, choices=[('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Traveller Cheque', 'Traveller Cheque'), ('Credit Card', 'Credit Card')], default=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='salutation',
            field=models.CharField(choices=[('Miss.', 'Miss.'), ('Mrs.', 'Mrs.'), ('Mr.', 'Mr.')], default='Mr.', max_length=20, null=True),
        ),
    ]
